rtl8723e-objs :=		\
		dm.o		\
		hw.o		\
		led.o		\
		phy.o		\
		rf.o		\
		sw.o		\
		table.o		\
		trx.o		\
		fw.o		\
		pwrseq.o	\
		pwrseqcmd.o	\

obj-$(CONFIG_RTL8723E) += rtl8723e.o

ccflags-y += -D__CHECK_ENDIAN__ 
