rtl8188ee-objs :=		\
	hw.o		\
	table.o		\
	sw.o		\
	trx.o		\
	led.o		\
	fw.o		\
	phy.o		\
	rf.o		\
	dm.o		\
	pwrseq.o	\
	pwrseqcmd.o

obj-$(CONFIG_RTL8192CE) += rtl8188ee.o

ccflags-y += -D__CHECK_ENDIAN__ 
